### ISSUE TITLE
Support conda for self contained Python environment

### ISSUE THREAD

**Issue by mithro** [idea-fasoc/datasheet-scrubber#2]
Datasheet scrubber requires Python 3.7 which is not generally available on long term release platforms. [Anaconda is a self contained Python environment](https://www.anaconda.com/). It is used heavily by data scientists and machine learning experts.

[An initial script could look like this one](https://github.com/timvideos/conda-hdmi2usb-packages/blob/master/conda-get.sh).

The minimal script could look something like
```bash
#!/bin/bash
wget -c https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
chmod a+x Miniconda3-latest-Linux-x86_64.sh
./Miniconda3-latest-Linux-x86_64.sh -p ./env -b -f
pip install -r requirements.txt 
# Or maybe python setup.py
# Or maybe pip install .
echo "Set path using;"
echo "export PATH=$PWD/env/bin:$$PATH"
```

Conda also [has support for "environment files"](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file)

Conda is also used heavily on Mac + Windows which don't ship with decent Python support.

**Comment by mithro** [comment]
FYI - I have a WIP patch which does this via the Makefile if you are interested.

**Comment by mortezafayazi** [comment]
Thanks Tim for your feedback. Yeah, I wanted to add Conda to my readme file but I could not find time. It's very good to add it. Thanks for your information about WIP patch. It seems very helpful.

**Comment by mortezafayazi** [comment]
Now it supports conda as well.

**Comment by mithro** [comment]
@mortezafayazi - You might consider using [my `make-env` tool](https://github.com/SymbiFlow/make-env).
